site: Not a site
url: blog.mediocreone.com
title: Just a blog
description: Piece of my mumbling.
twitter:
  username: mediocre_one
  card: summary
  creator: mediocre_one
author:
  twitter: mediocre_one
  name: mediocre_one
  avatar:
  email: one@mediocreone.com
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"